//Scripted Pipeline
node('node1-label') {
    stage('Source') { //Get the code
        git 'https://github.com/kiranpithani/jenkins'
    }
    stage('Build') {//Compile the code and run unit tests and create package
        sh 'mvn clean package'
    }
}