node('jdk11-mvn3.8.4') {
    try {
        properties([parameters([choice(choices: ['scripted', 'master', 'declarative'], description: 'branch to be built', name: 'BRANCH_TO_BUILD')])])
        stage('git') {
            git url: 'https://github.com/GitPracticeRepo/java11-examples.git'
        }
        stage('build') {
            sh '/usr/local/apache-maven-3.8.4/bin/mvn clean package'
        }
    }
}